name: Nyaa Scraper

on:
  workflow_dispatch:
    inputs:
      id_range:
        description: 'The range of torrent IDs to scrape (format: id_start-id_end)'
        required: true
        default: '12847-13748'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Nyaa Scraper
      run: python nyaa_scraper.py ${{ github.event.inputs.id_range }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: torrent-info
        path: |
          *.json
